<?php

declare(strict_types=1);

namespace Waaseyaa\Entity\Tests\Unit;

use Waaseyaa\Entity\EntityBase;
use Waaseyaa\Entity\EntityInterface;
use PHPUnit\Framework\TestCase;

/**
 * @covers \Waaseyaa\Entity\EntityBase
 */
class EntityBaseTest extends TestCase
{
    public function testImplementsInterface(): void
    {
        $entity = new TestEntity();

        $this->assertInstanceOf(EntityInterface::class, $entity);
        $this->assertInstanceOf(EntityBase::class, $entity);
    }

    public function testDefaultEntityTypeId(): void
    {
        $entity = new TestEntity();

        $this->assertSame('test_entity', $entity->getEntityTypeId());
    }

    public function testEntityTypeIdFromConstructor(): void
    {
        $entity = new TestEntity(entityTypeId: 'custom_type');

        $this->assertSame('custom_type', $entity->getEntityTypeId());
    }

    public function testIdReturnsNullWhenNotSet(): void
    {
        $entity = new TestEntity();

        $this->assertNull($entity->id());
    }

    public function testIdReturnsValueFromDefaultKey(): void
    {
        $entity = new TestEntity(['id' => 42]);

        $this->assertSame(42, $entity->id());
    }

    public function testIdReturnsValueFromCustomKey(): void
    {
        $entity = new TestEntity(
            values: ['nid' => 7],
            entityKeys: ['id' => 'nid'],
        );

        $this->assertSame(7, $entity->id());
    }

    public function testUuidAutoGenerated(): void
    {
        $entity = new TestEntity();
        $uuid = $entity->uuid();

        $this->assertNotEmpty($uuid);
        // UUID v4 format: xxxxxxxx-xxxx-4xxx-[89ab]xxx-xxxxxxxxxxxx
        $this->assertMatchesRegularExpression(
            '/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/',
            $uuid,
        );
    }

    public function testUuidPreservedWhenProvided(): void
    {
        $providedUuid = 'a1b2c3d4-e5f6-4a7b-8c9d-e0f1a2b3c4d5';
        $entity = new TestEntity(['uuid' => $providedUuid]);

        $this->assertSame($providedUuid, $entity->uuid());
    }

    public function testUuidUsesCustomKey(): void
    {
        $providedUuid = 'a1b2c3d4-e5f6-4a7b-8c9d-e0f1a2b3c4d5';
        $entity = new TestEntity(
            values: ['my_uuid' => $providedUuid],
            entityKeys: ['uuid' => 'my_uuid'],
        );

        $this->assertSame($providedUuid, $entity->uuid());
    }

    public function testLabel(): void
    {
        $entity = new TestEntity(['label' => 'My Entity']);

        $this->assertSame('My Entity', $entity->label());
    }

    public function testLabelDefaultsToEmptyString(): void
    {
        $entity = new TestEntity();

        $this->assertSame('', $entity->label());
    }

    public function testLabelCustomKey(): void
    {
        $entity = new TestEntity(
            values: ['title' => 'Custom Title'],
            entityKeys: ['label' => 'title'],
        );

        $this->assertSame('Custom Title', $entity->label());
    }

    public function testBundleDefaultsToEntityTypeId(): void
    {
        $entity = new TestEntity();

        $this->assertSame('test_entity', $entity->bundle());
    }

    public function testBundleFromValues(): void
    {
        $entity = new TestEntity(
            values: ['bundle' => 'article'],
        );

        $this->assertSame('article', $entity->bundle());
    }

    public function testBundleCustomKey(): void
    {
        $entity = new TestEntity(
            values: ['type' => 'page'],
            entityKeys: ['bundle' => 'type'],
        );

        $this->assertSame('page', $entity->bundle());
    }

    public function testIsNewWhenNoId(): void
    {
        $entity = new TestEntity();

        $this->assertTrue($entity->isNew());
    }

    public function testIsNotNewWhenHasId(): void
    {
        $entity = new TestEntity(['id' => 1]);

        $this->assertFalse($entity->isNew());
    }

    public function testEnforceIsNew(): void
    {
        $entity = new TestEntity(['id' => 1]);
        $this->assertFalse($entity->isNew());

        $entity->enforceIsNew(true);
        $this->assertTrue($entity->isNew());

        $entity->enforceIsNew(false);
        $this->assertFalse($entity->isNew());
    }

    public function testEnforceIsNewReturnsSelf(): void
    {
        $entity = new TestEntity();
        $result = $entity->enforceIsNew(true);

        $this->assertSame($entity, $result);
    }

    public function testToArray(): void
    {
        $values = ['id' => 1, 'label' => 'Test'];
        $entity = new TestEntity($values);

        $array = $entity->toArray();

        $this->assertSame(1, $array['id']);
        $this->assertSame('Test', $array['label']);
        // UUID is auto-generated.
        $this->assertArrayHasKey('uuid', $array);
    }

    public function testLanguageDefault(): void
    {
        $entity = new TestEntity();

        $this->assertSame('en', $entity->language());
    }

    public function testLanguageFromValues(): void
    {
        $entity = new TestEntity(['langcode' => 'fr']);

        $this->assertSame('fr', $entity->language());
    }

    public function testLanguageCustomKey(): void
    {
        $entity = new TestEntity(
            values: ['lang' => 'de'],
            entityKeys: ['langcode' => 'lang'],
        );

        $this->assertSame('de', $entity->language());
    }

    public function testStringId(): void
    {
        $entity = new TestEntity(['id' => 'my_string_id']);

        $this->assertSame('my_string_id', $entity->id());
        $this->assertFalse($entity->isNew());
    }
}
